config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :payment_requests
  resources :payment_request_users, only: [:update]

  root to: 'payment_requests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment_request.rb
class PaymentRequest < ApplicationRecord
  belongs_to :requestor, class_name: 'User', primary_key: 'id', foreign_key: "user_id"
  has_many :payment_request_users
  has_many :approvers, through: :payment_request_users, source: :user

  def self.without_status
    self.joins(:payment_request_users).where(payment_request_users:{status:nil}).uniq
  end

end

app/models/payment_request_user.rb
class PaymentRequestUser < ApplicationRecord
  belongs_to :payment_request
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :payment_requests_as_requestor, class_name: 'PaymentRequest', foreign_key: 'user_id'

  has_many :payment_request_users
  has_many :payment_requests_as_approver, through: :payment_request_users, source: :payment_request
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/payment_request_users_controller.rb
class PaymentRequestUsersController < ApplicationController
    def update
        payment_request_user = PaymentRequestUser.where(id:params[:id])
        payment_request_user.update(status:params[:status])
        redirect_to root_path
    end
end

app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController

  def index
    @payment_requests_i_created = current_user.payment_requests_as_requestor

    @payment_requests_needing_my_approval = current_user.payment_requests_as_approver.without_status
  end

  def new
  end

  def create
    approver_ids = params[:payment_request][:approvers]
    has_two_approvers = approver_ids.present? && approver_ids.length >= 2
    if has_two_approvers
      payment_request = current_user.payment_requests_as_requestor.create(payment_request_params)
      params[:payment_request][:approvers].each do |id|
        user = User.find(id)
        payment_request.approvers << user
      end
    else
      flash[:error] = "You need at least 2 approvers"
    end

    redirect_to root_path
  end


  private
    def payment_request_params
      params.require(:payment_request).permit(:description, :amount)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FamilyPay
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-white.border-bottom.box-shadow
      %h5.my-0.mr-md-auto.font-weight-normal Family Pay
      %nav.my-2.my-md-0.mr-md-3
        - if user_signed_in?
          = current_user.email
          = link_to('Logout', destroy_user_session_path, method: :delete)
        - else
          = link_to('Sign In', new_user_session_path)

    -if flash[:error].present?
      .alert.alert-danger
        = flash[:error]
    = yield

app/views/payment_requests/index.html.haml
.container
  .row.mb-5
    .col-12
      .card
        .card-header
          %h3 Actions I need to take
        .card-body
          .list-group
            - if @payment_requests_needing_my_approval.empty?
              Yay, you are all caught up
            - else
              .table-responsive
                %table.table.table-striped
                  %thead
                    %tr
                      %th{:scope => "col"} Status
                      %th{:scope => "col"} Description
                      %th{:scope => "col"} Amount
                      %th{:scope => "col"} Actions
                  %tbody

                    - @payment_requests_needing_my_approval.each do |request|
                      %tr
                        %td
                          = request.status&.titleize
                        %td
                          = request.description
                        %td
                          = number_to_currency(request.amount)
                        %td.text-right
                          - id = request.payment_request_users.where(user_id:current_user.id).first.id
                          = link_to "approve", payment_request_user_path(id, status:"approved"), method: :put, class: 'text-primary'
                          |
                          = link_to "decline", payment_request_user_path(id, status:"declined"), method: :put, class: 'text-danger'


  .row
    .col-12
      .card
        .card-header
          .float-left
            %h3 Requests I created
          .float-right
            = link_to new_payment_request_path do
              .btn.btn-success Create Request
        .card-body
          .list-group
            .table-responsive
              %table.table.table-striped
                %thead
                  %tr
                    %th{:scope => "col"} Status
                    %th{:scope => "col"} Description
                    %th{:scope => "col"} Amount
                    %th{:scope => "col"} Approvers
                %tbody
                  - @payment_requests_i_created.each do |request|
                    %tr
                      %td
                        = request.status&.titleize
                      %td
                        = request.description
                      %td
                        = number_to_currency(request.amount)
                      %td
                        = request.approvers.map{|u| u.email }

app/views/payment_requests/new.html.haml
.container
  .row.justify-content-center
    .col-8
      .card
        .card-body
          %h4 New Payment Request
          = form_for :payment_request, url: payment_requests_path, method: :post do |f|
            .form-group
              %label Description
              = f.text_field :description, class: 'form-control', placeholder: 'I need a new glider'
            .form-group
              %label Amount
              = f.text_field :amount, class: 'form-control', placeholder: '10'

            .form-group
              %label Approver(s)
              %br
              - User.all.each do |user|
                - next if user == current_user
                %label
                  = check_box_tag 'payment_request[approvers][]', user.id
                  = user.email
                %br

            .form-group
              = f.submit "Create & Send", class: 'btn btn-success'